Modificar a página inicial da documentação
fga-eps-mds/2023-1-CAPJu-Doc pull request #126
Opened 2023-05-16 02:16 UTC by OscarDeBrito

## Issue
Atualmente a página inical da documentação do github pages é a padrão do MKdocs, portanto é necessário modficá-la para apresentação do projeto e de seus integrantes.

Closes fga-eps-mds/2023-1-CAPJu-Doc#125

## Descrição
 Modifiquei a página inicial da documentação para apresentar a descrição do projeto e seus contribuidores.

## Revisão 

- [ ]  Descrever o projeto 
- [ ]  Descrever a equipe

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-05-16 23:27 UTC, faco400 reviewed
Achei massa galera. Só uma sugestão que vi com base nos dos semestres passados é só separar os integrantes em EPS e MDS. Só pra ficar claro quem é de qual turma mesmo

2023-05-17 01:40 UTC, OscarDeBrito commented
> Achei massa galera. Só uma sugestão que vi com base nos dos semestres passados é só separar os integrantes em EPS e MDS. Só pra ficar claro quem é de qual turma mesmo

Obrigado Vinicius, fizemos a alteração. @faco400

2023-05-17 01:50 UTC, faco400 submitted a review, later dismissed
Boa! Tá Aprovado

2023-05-17 02:12 UTC, OscarDeBrito commented
> Boa! Tá Aprovado

Vinicius, o monitor tava ajudando a gente aqui com os commits e cancelou a aprovação. @faco400

2023-05-17 16:39 UTC, sergiosacj requested changes
Só falta colocar a logo do projeto na página inicial.

2023-05-17 23:52 UTC, artur-jack commented
> Ah, já ia esquecendo, também falta listar nossos repositórios.

Já fizemos as alterações.

2023-05-18 19:55 UTC, senaarth approved these changes
Aprovado!

2023-05-18 22:45 UTC, merged