Subir Gihtub Pages
fga-eps-mds/2023-1-CAPJu-Doc pull request #13
Opened 2023-04-15 18:42 UTC by faco400

# Subir Gihtub Pages 

## Issue fga-eps-mds/2023-1-CAPJu-Doc#3
Cria link do gh-pages
Closes fga-eps-mds/2023-1-CAPJu-Doc#3

## Descrição
Criação do link e acesso ao gihub-pages do projeto Capju 2023/1

2023-04-15 23:35 UTC, wellpriz approved these changes
Alterações aprovadas

2023-04-16 00:00 UTC, RodrigoTCLima approved these changes
Aprovado!

2023-04-17 02:07 UTC, senaarth requested changes
Galera, não ficou documento como rodar localmente, acho que vale escrever no readme.

2023-04-17 15:32 UTC, RodrigoTCLima approved these changes

2023-04-17 15:40 UTC, senaarth approved these changes
LGTM!

2023-04-17 15:41 UTC, merged