(#22) - Adiciona documento de Planejamento de Custos
fga-eps-mds/2023-1-CAPJu-Doc pull request #24
Opened 2023-04-24 23:06 UTC by RodrigoTCLima

# Documentar eventos Pré-Projeto

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#22

## Descrição

Criação do documento de Planejamento de Custos.

2023-04-25 03:23 UTC, victordsantoss reviewed
O iframe não está sendo renderizado, pois o link para a planilha docs não pode ser encontrado.

2023-04-25 12:25 UTC, faco400 requested changes

2023-04-25 23:39 UTC, victordsantoss submitted a review, later dismissed
Muito bom, gostei!

2023-04-29 01:42 UTC, RodrigoTCLima commented
Realizar atualização conforme custo por hora de manter um aluno numa faculdade pública federal, pode-se usar o valor dado pelo https://www.scielo.br/j/es/a/3SxH5sZPhCxRKc5KBqyNZvd/# .

2023-05-02 12:08 UTC, senaarth commented
Como está o andamento desse?

2023-05-04 01:51 UTC, RodrigoTCLima commented
@senaarth, agora só esperando o revew.

2023-05-04 02:18 UTC, faco400 approved these changes
Opa! Muito bom. LGTM!

2023-05-04 03:54 UTC, victordsantoss approved these changes
Aprovado!

2023-05-04 03:58 UTC, victordsantoss approved these changes

2023-05-04 03:58 UTC, victordsantoss approved these changes
As correções estão de acordo.

2023-05-04 03:58 UTC, merged