Criar documento de backlog do produto #42
fga-eps-mds/2023-1-CAPJu-Doc pull request #48
Opened 2023-05-01 19:29 UTC by victordsantoss

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#42

## Descrição

Cria o documento do backlog do produto e o adiciona no github pages.

## Revisão 

 - [ ] Épico
 - [ ] Histórias de Usuário
 - [ ] Adicionar documento no Github Pages

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

## Screenshots (Se necessário)

| Antes | Depois |
| ----- | ------ |
| NÃO TINHA  | ![Captura de Tela 2023-05-01 às 16 00 47](https://user-images.githubusercontent.com/52058094/235515981-757c3d77-44d4-4e15-b109-8a4ceaed3208.png) |

2023-05-01 19:58 UTC, zpeniel09 reviewed
Caro @victordsantoss  segue os comentários deixado lá por @sergiosacj para corrigir o documento.

2023-05-02 12:06 UTC, senaarth requested changes
Fala Victor, acredito que não tenho muito a acrescentar além do Sérgio, tenho apenas uma dúvida, não deveria haver um épico de Usabilidade?

2023-05-02 13:44 UTC, victordsantoss commented
@sergiosacj Os ajustes foram corrigidos e estão disponíveis para uma nova revisão.

2023-05-02 13:46 UTC, victordsantoss commented
@senaarth os épicos foram baseados no Lean Inception, por isso acabou não tendo o tópico de usabilidade, mas é uma pauta que podemos discutir.

2023-05-02 17:32 UTC, sergiosacj commented
@victordsantoss, quando falei da US04 e da US05, usei "para que eu possa" no texto apenas para indicar a coluna da tabela. Pode remover isso do texto desses campos.

Fora isso, tudo ok! Valeu.

2023-05-02 21:39 UTC, victordsantoss commented
@sergiosacj Corrigido!

2023-05-02 21:46 UTC, zpeniel09 approved these changes

2023-05-05 17:11 UTC, merged